config/routes.rb
PhotoWall::Application.routes.draw do
  
  root :to => 'photos#index'
  
  resources :photos do
    collection do
      get 'random/:seed', :action => 'random', :as => 'random'
    end
  end
  

end

app/models/color.rb
class Color < ActiveRecord::Base
  validates_presence_of :red, :green, :blue
  validates_numericality_of :red, :green, :blue
  validates :red, :green, :blue, :inclusion => { :in => 0..255 }

  has_many :palette_entries
  has_many :photos, :through => :palette_entries

  def to_hex
    "#%02X%02X%02X" % [red, green, blue]
  end
end

app/models/palette_entry.rb
class PaletteEntry < ActiveRecord::Base
  attr_accessible :position, :color_id, :photo_id
  belongs_to :color
  belongs_to :photo

  before_save :set_position

  def set_position
    max_position = photo.palette_entries.map { |pe| pe.position }.max || 0
    self.position = max_position + 1
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base

  mount_uploader :file, PhotoUploader

  attr_accessible :file
  has_many :palette_entries
  has_many :colors, :through => :palette_entries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  respond_to :html, :json
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  
  def index
    respond_with @photos = Photo.page(params[:page]).per(16)
  end
  
  def random
    # ensure that the seed is a single place decimal
    seed = Float(params[:seed].to_i % 10) / 10
    # use the seed to ensure pagination is performed without duplicates
    Photo.connection.execute "select setseed(#{seed})"
    # perform the search using random and the seed
    respond_with @photos = Photo.order('random()').page(params[:page]).per(16)
  end
  
  def show
    respond_with @photo = Photo.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def rand_seed
    params[:seed] || rand(10)
  end
  
end

app/views/application/_head.html.haml
%head
  %meta{ :charset => "utf-8" }/
  %meta{ 'http-equiv' => 'X-UA-Compatible', :content => 'IE=edge,chrome=1' }/

  %title Photo Wall
  
  %meta{ :name => "description", :content => "" }/
  %meta{ :name => "viewport", :content => "width=device-width" }/
  %meta{ :name => 'author', :content => 'Blake Hilscher, blake@hilscher.ca' }
  
  = stylesheet_link_tag    "application", :media => "all"
  = javascript_include_tag "application"
  = csrf_meta_tag
  
  -# asynchronous google analytics: mathiasbynens.be/notes/async-analytics-snippet
  -# Looks for google_account_id first in ENV['GOOGLE_ACCOUNT_ID'] then in config/html5_rails.yml
  - if !google_account_id.blank?
    :javascript
      var _gaq=[['_setAccount','#{ google_account_id }'],['_trackPageview']];
      (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
      g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
      s.parentNode.insertBefore(g,s)}(document,'script'));

app/views/application/_header.html.haml
#header
  .button.github
    .icon-github
    = link_to "Fork on Github", "https://github.com/blakehilscher/Photo-Wall"
  
  .button.random{:class => "#{'active' if params[:seed]}"}
    %i.icon-random
    = link_to 'Random', random_photos_path(rand_seed)

app/views/layouts/_head.html.haml
%head
  %meta{ :charset => "utf-8" }/
  %meta{ 'http-equiv' => 'X-UA-Compatible', :content => 'IE=edge,chrome=1' }/

  %title Photo Wall
  
  %meta{ :name => "description", :content => "" }/
  %meta{ :name => "viewport", :content => "width=device-width" }/
  
  = stylesheet_link_tag    "application", :media => "all"
  = javascript_include_tag "application"
  = csrf_meta_tag
  
  -# asynchronous google analytics: mathiasbynens.be/notes/async-analytics-snippet
  -# Looks for google_account_id first in ENV['GOOGLE_ACCOUNT_ID'] then in config/html5_rails.yml
  - if !google_account_id.blank?
    :javascript
      var _gaq=[['_setAccount','#{ google_account_id }'],['_trackPageview']];
      (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
      g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
      s.parentNode.insertBefore(g,s)}(document,'script'));

app/views/layouts/application.html.haml
!!! 5
- html_tag :lang => "en" do
  = render "application/head"
  %body
    #container
      = render "application/header"
      
      #main{:role => "main"}= yield
      
      = render "application/footer"

app/views/photos/_photo.html.haml
%li.photo{:class => cycle('first','second','third','fourth') }
  .photo_inner
    = link_to( image_tag( photo.file_url(:thumb) ), photo_path(photo) )

app/views/photos/_photos.html.haml
- pagination = paginate photos
.collection-pagination.top= pagination
%ul.collection.photos= render photos
.collection-pagination= pagination

app/views/photos/index.html.haml
.collection-pagination.top= paginate @photos
%ul.collection.photos
  - @photos.each do |photo|
    %li.photo{:class => cycle('first','second','third','fourth') }
      .photo_inner
        = link_to( image_tag( photo.file_url(:thumb) ), photo_path(photo) )
        
.collection-pagination= paginate @photos

app/views/photos/random.html.haml
= render :partial => 'photos', :locals => {:photos => @photos}

app/views/photos/show.html.haml
.record.photo= link_to( image_tag( @photo.file_url ), @photo.file_url, :target => '_blank' )
-@photo.colors.each do |color|
  .box{:style => "width:75px;height:75px;float:left;margin:10px;background-color:#{color.to_hex}"}
    &nbsp;